### PR TITLE
Add missing `DialogProperties` argument

### PR DESCRIPTION
**Pull request by blipinsk**
`DialogProperties` argument was missing from `dialog` extensions for `NavGraphBuilder`.
This PR fixes the problem (and updates the binary API file).

### CODE REVIEW

**Review by hrach — COMMENTED** [review]
LGTM, but could you please recreate the previous function without the argument to maintain binary compatibility? Make that function deprecated-hidden, please.

**Comment by blipinsk** [comment]
sure thing @hrach! done ✅ 

1. Do you have any preference regarding the body of those functions? should those be recreated as well? or would you prefer them to redirect to the new functions?
2. Why don't I extract all `deprecated-hidden` functions to a separate file? Something like `NavBuilderDeprecated.kt` or `NavBuilderLegacy.kt`, to separate "current" from "outdated" api.

**Review by hrach — APPROVED** [review]

**Comment by blipinsk** [comment]
@hrach I pushed a fix for a lint issue, you'll need to enable the auto-merge again

**Comment by blipinsk** [comment]
@hrach is there any timeline for the next release of the library (which will consist those ☝️ changes)?

**Comment by hrach** [comment]
0.10.0 successfully deployed to maven central, wait a few minutes for propagation.
https://github.com/kiwicom/navigation-compose-typed/actions/runs/8004387187/job/21861670122

**Pull request merged**
